#!/bin/bash
#
# mysqld-exporter   Startup script for the mysqld-exporter monitoring agent
#
# chkconfig:   2345 15 85
# description: mysqld-exporter - Data collection agent for apptuit.ai
# processname: mysqld-exporter
# pidfile: /var/run/prometheus/mysqld_exporter/mysqld-exporter.pid
#
### BEGIN INIT INFO
# Provides: mysqld-exporter
# Required-Start: $local_fs $remote_fs $network $named
# Required-Stop: $local_fs $remote_fs $network
# Short-Description: mysqld-exporter - Data collection agent for apptuit.ai
# Description: mysqld-exporter - Data collection agent for apptuit.ai
### END INIT INFO

# Source function library.
. /etc/init.d/functions

THIS_HOST=`hostname`
MYSQLD_EXPORTER=${MYSQLD_EXPORTER-/opt/prometheus/mysqld_exporter/bin/mysqld_exporter}
PIDFILE=${PIDFILE-/var/run/prometheus/mysqld_exporter/mysqld_exporter.pid}
LOGFILE=${LOGFILE-/var/log/prometheus/mysqld_exporter/mysqld_exporter.log}

RUN_AS_USER=${RUN_AS_USER-prometheus}
RUN_AS_GROUP=${RUN_AS_GROUP-prometheus}

prog=mysqld_exporter
if [ -f /etc/sysconfig/$prog ]; then
  . /etc/sysconfig/$prog
fi

if [ -z "$OPTIONS" ]; then
  OPTIONS="${OPTIONS} --config.my-cnf=/etc/mysqld_exporter/my.cnf"
fi

sanity_check() {
  for file in "$PIDFILE" "$LOGFILE"; do
    parentdir=`dirname "$file"`
    if [ ! -d "$parentdir" ]; then
      install -m 755 -o $RUN_AS_USER -g $RUN_AS_GROUP -d $parentdir
    fi
  done
}

start() {
  echo -n $"Starting $prog: "
  sanity_check || return $?
  su - ${RUN_AS_USER} -c "nohup $MYSQLD_EXPORTER $OPTIONS >> $LOGFILE 2>&1 &"
  echo $(pidof mysqld_exporter) > ${PIDFILE}
  read PID < "${PIDFILE}"
  RETVAL=$?
  echo "Running as PID ${PID}"
  return $RETVAL
}

# When stopping mysqld-exporter a delay of ~15 seconds before SIGKILLing the
# process so as to give enough time for mysqld-exporter to SIGKILL any errant
# collectors.
stop() {
  echo -n $"Stopping $prog: "
  sanity_check || return $?
  killproc -p $PIDFILE -d 15 $MYSQLD_EXPORTER
  RETVAL=$?
  echo
  return $RETVAL
}

# See how we were called.
case "$1" in
  start) start;;
  stop) stop;;
  status)
    status -p $PIDFILE $MYSQLD_EXPORTER
    RETVAL=$?
    ;;
  restart|force-reload|reload) stop && start;;
  condrestart|try-restart)
    if status -p $PIDFILE $MYSQLD_EXPORTER >&/dev/null; then
      stop && start
    fi
    ;;
  *)
    echo $"Usage: $prog {start|stop|status|restart|force-reload|reload|condrestart|try-restart}"
    RETVAL=2
esac

exit $RETVAL