#!/bin/bash
#
# memcached-exporter   Startup script for the memcached-exporter monitoring agent
#
# chkconfig:   2345 15 85
# description: memcached-exporter - Data collection agent for apptuit.ai
# processname: memcached-exporter
# pidfile: /var/run/prometheus/memcached_exporter/memcached-exporter.pid
#
### BEGIN INIT INFO
# Provides: memcached-exporter
# Required-Start: $local_fs $remote_fs $network $named
# Required-Stop: $local_fs $remote_fs $network
# Short-Description: memcached-exporter - Data collection agent for apptuit.ai
# Description: memcached-exporter - Data collection agent for apptuit.ai
### END INIT INFO

# Source function library.
. /etc/init.d/functions

if [ -r /etc/default/memcached-exporter ]
then
	. /etc/default/memcached-exporter
fi

THIS_HOST=`hostname`
MEMCACHED_EXPORTER_BINARY=${MEMCACHED_EXPORTER_BINARY-/opt/prometheus/memcached_exporter/bin/memcached_exporter}
PIDFILE=${PIDFILE-/var/run/prometheus/memcached_exporter/memcached_exporter.pid}
LOGFILE=${LOGFILE-/var/log/prometheus/memcached_exporter/memcached_exporter.log}

RUN_AS_USER=${RUN_AS_USER-prometheus}
RUN_AS_GROUP=${RUN_AS_GROUP-prometheus}

prog=memcached_exporter
if [ -f /etc/sysconfig/$prog ]; then
  . /etc/sysconfig/$prog
fi

sanity_check() {
  for file in "$PIDFILE" "$LOGFILE"; do
    parentdir=`dirname "$file"`
    if [ ! -d "$parentdir" ]; then
      install -m 755 -o $RUN_AS_USER -g $RUN_AS_GROUP -d $parentdir
    fi
  done
}

start() {
  echo -n $"Starting $prog: "
  sanity_check || return $?
  su - ${RUN_AS_USER} -s /bin/bash -c "DATA_SOURCE_NAME=\"$DATA_SOURCE_NAME\" EXPORTER_FLAGS=\"$EXPORTER_FLAGS\" nohup $MEMCACHED_EXPORTER_BINARY $EXPORTER_FLAGS >> $LOGFILE 2>&1 &"
  echo $(pidof memcached_exporter) > ${PIDFILE}
  read PID < "${PIDFILE}"
  RETVAL=$?
  echo "Running as PID ${PID}"
  return $RETVAL
}

# When stopping memcached-exporter a delay of ~15 seconds before SIGKILLing the
# process so as to give enough time for memcached-exporter to SIGKILL any errant
# collectors.
stop() {
  echo -n $"Stopping $prog: "
  sanity_check || return $?
  killproc -p $PIDFILE -d 15 $MEMCACHED_EXPORTER_BINARY
  RETVAL=$?
  echo
  return $RETVAL
}

# See how we were called.
case "$1" in
  start) start;;
  stop) stop;;
  status)
    status -p $PIDFILE $MEMCACHED_EXPORTER_BINARY
    RETVAL=$?
    ;;
  restart|force-reload|reload) stop && start;;
  condrestart|try-restart)
    if status -p $PIDFILE $MEMCACHED_EXPORTER_BINARY >&/dev/null; then
      stop && start
    fi
    ;;
  *)
    echo $"Usage: $prog {start|stop|status|restart|force-reload|reload|condrestart|try-restart}"
    RETVAL=2
esac

exit $RETVAL