#!/bin/sh
#
# mysqld-exporter   Startup script for the Prometheus mysqld exporter
#
# chkconfig:   2345 15 85
# description: mysqld-exporter - Prometheus MySQL metrics exporter for apptuit.ai
# processname: mysqld-exporter
#
### BEGIN INIT INFO
# Provides:          mysqld-exporter
# Required-Start:    $network $mysql
# Required-Stop:     $network $mysql
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: mysqld-exporter - Prometheus MySQL metrics exporter for apptuit.ai
### END INIT INFO

WORKING_DIR=/opt/prometheus/mysqld_exporter
DAEMON="${WORKING_DIR}/bin/mysqld_exporter"

. /lib/lsb/init-functions

PIDFILE=${PIDFILE-"/var/run/prometheus/mysqld_exporter/mysqld_exporter.pid"}
CNFFILE=${CNFFILE-"/etc/mysqld_exporter/my.cnf"}

RUN_AS_USER=${RUN_AS_USER-prometheus}
RUN_AS_GROUP=${RUN_AS_GROUP-prometheus}

sanity_check() {
  for file in "$PIDFILE"; do
    parentdir=`dirname "$file"`
    if [ ! -d "$parentdir" ]; then
      install -m 755 -o $RUN_AS_USER -g $RUN_AS_GROUP -d $parentdir
    fi
  done
}

case $1 in
    start)
        log_daemon_msg "Starting mysqld-exporter"
        sanity_check || return $?

        start-stop-daemon --start --quiet -u $RUN_AS_USER \
            --pidfile "$PIDFILE" --chuid $RUN_AS_USER:$RUN_AS_GROUP \
            --background --make-pidfile --startas $DAEMON -- \
            --config.my-cnf="$CNFFILE"

        log_end_msg $?
        ;;
    stop)
        log_daemon_msg "Stopping mysqld-exporter"
        if [ ! -f "$PIDFILE" ]; then
            log_failure_msg "$PIDFILE doesn't exist. mysqld-exporter not running?"
            exit 0
        fi
        start-stop-daemon --stop --retry 30 --quiet --oknodo -u $RUN_AS_USER --pidfile "$PIDFILE" && rm -f "$PIDFILE"
        rv=$?
        log_end_msg 0
        exit $rv
        ;;
    restart|force-reload)
        $0 stop && $0 start
        ;;
    status)
        status_of_proc -p $PIDFILE "$DAEMON" "mysqld-exporter"
        exit $?
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|force-reload|status}"
        exit 2
        ;;
esac
