#!/bin/sh
#
# elasticsearch_exporter   Startup script for the Prometheus node exporter
#
# chkconfig:   2345 15 85
# description: elasticsearch_exporter - Prometheus Node metrics exporter for apptuit.ai
# processname: elasticsearch_exporter
# pidfile: /var/run/prometheus/elasticsearch_exporter/elasticsearch_exporter.pid
#
### BEGIN INIT INFO
# Provides:          elasticsearch_exporter
# Required-Start:    $network $remote_fs
# Required-Stop:     $network $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: elasticsearch_exporter - Prometheus Node metrics exporter for apptuit.ai
### END INIT INFO

WORKING_DIR=/opt/prometheus/node_exporter
DAEMON="${WORKING_DIR}/elasticsearch_exporter"

. /lib/lsb/init-functions

PIDFILE=${PIDFILE-"/var/run/prometheus/elasticsearch_exporter/elasticsearch_exporter.pid"}

RUN_AS_USER=${RUN_AS_USER-prometheus}
RUN_AS_GROUP=${RUN_AS_GROUP-prometheus}

sanity_check() {
  for file in "$PIDFILE"; do
    parentdir=`dirname "$file"`
    if [ ! -d "$parentdir" ]; then
      install -m 755 -o $RUN_AS_USER -g $RUN_AS_GROUP -d $parentdir
    fi
  done
}

case $1 in
    start)
        log_daemon_msg "Starting elasticsearch_exporter"
        sanity_check || return $?

        start-stop-daemon --start --quiet -u $RUN_AS_USER \
            --pidfile "$PIDFILE" --chuid $RUN_AS_USER:$RUN_AS_GROUP \
            --background --make-pidfile --startas $DAEMON

        log_end_msg $?
        ;;
    stop)
        log_daemon_msg "Stopping elasticsearch_exporter"
        if [ ! -f "$PIDFILE" ]; then
            log_failure_msg "$PIDFILE doesn't exist. elasticsearch_exporter not running?"
            exit 0
        fi
        start-stop-daemon --stop --retry 30 --quiet --oknodo -u $RUN_AS_USER --pidfile "$PIDFILE" && rm -f "$PIDFILE"
        rv=$?
        log_end_msg 0
        exit $rv
        ;;
    restart|force-reload)
        $0 stop && $0 start
        ;;
    status)
        status_of_proc -p $PIDFILE "$DAEMON" "elasticsearch_exporter"
        exit $?
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|force-reload|status}"
        exit 2
        ;;
esac
