#!/bin/bash

is_systemd=0

if [ -d /run/systemd/system ]; then
   is_systemd=1
fi

PROMETHEUS_USER="prometheus"
PROMETHEUS_GROUP="prometheus"

if [ -z "$(getent group $PROMETHEUS_GROUP)" ]; then
  groupadd --system $PROMETHEUS_GROUP
else
  echo "Group [$PROMETHEUS_GROUP] already exists"
fi

if [ -z "$(id $PROMETHEUS_USER)" ]; then
  useradd --system --home-dir /home/prometheus --no-create-home \
  -g $PROMETHEUS_GROUP --shell /sbin/nologin $PROMETHEUS_USER
else
  echo "User [$PROMETHEUS_USER] already exists"
fi

chown -R $PROMETHEUS_USER:$PROMETHEUS_GROUP /etc/default/mysqld-exporter
chmod 600 /etc/default/mysqld-exporter

mkdir -p /var/log/prometheus/mysqld_exporter
chown -R $PROMETHEUS_USER.$PROMETHEUS_GROUP /var/log/prometheus/mysqld_exporter

if [ $is_systemd -eq 1 ]
then
	systemctl daemon-reload && systemctl enable mysqld-exporter
fi
